### PR TITLE
Null safety

### PR DESCRIPTION
**Pull request by hovadur**

### CODE REVIEW

**Comment by Leptopoda** [comment]
You should probably also update the example shown in the README

**Comment by hovadur** [comment]
> You should probably also update the example shown in the README

done

**Comment by M123-dev** [comment]
Ping @Darshan0

**Comment by juanagu** [comment]
Ping @Darshan0

**Comment by juanagu** [comment]
Hey @Darshan0 I hope you are doing well, when will be this feature available as release?

**Pull request merged**
